astrotest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
# IMAGE SERVING IN DEVELOPMENT
from django.conf import settings
from django.conf.urls.static import static

app_url_patterns = [
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('exams/', include('exams.urls')),
]

base_url_patterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')), # django-smart-selects
]

urlpatterns = app_url_patterns + base_url_patterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
        url(r'^$', views.main, name="main"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def main(request):
    return render(request, "main/main.html")

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <!-- META TAGS -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Welcome to astrotest!">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" >

    <!-- FONTS -->
	<!--<link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">-->
    <!--<link href="https://fonts.googleapis.com/css?family=Fira+Sans|Fira+Sans+Condensed" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300|Roboto" rel="stylesheet">

    <!-- CUSTOM CSS -->
	<link href="{% static 'css/dashboard.css' %}" rel="stylesheet" type="text/css">

    <!-- Section to extend the header information on a particular page -->
    {% block extrahead %}{% endblock %}

    <!-- For sticky headers -->
	<!--
    <style>
    .sticky {
      position: -webkit-sticky;
      position: -moz-sticky;
      position: -ms-sticky;
      position: -o-sticky;
      position: sticky;
      z-index: 100;
    }
    </style>
	-->


    <!-- Extends the header -->
    <title>{% block title %}{% endblock %}</title>

</head>

<body>

	{% include "main/sidebar.html" %}
	{% block content %}{% endblock %}





    <!-- JavaScript if I need it anywhere-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>



</body>



</html>

main/templates/main/main.html
{% extends "main/base.html" %}
{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Dashboard for {{ request.user.first_name }} {{ request.user.last_name }}</h1>

</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h4">Overview</h1>

</div>


</main>
{% endblock %}

main/templates/main/reports.html
{% extends "tutoring/base.html" %}
{% block title %} Reports
{% endblock %}
{% block extrahead %}
{% endblock %}


{% block content %}

{% for report in reports %}
<h1>{{ report }}</h1>
	{% autoescape off %}
	<div>
		{{ report.content }}
	<div>
	{% endautoescape %}
{% endfor %}

{% endblock %}

main/templates/main/sidebar.html
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'main:main' %}">astrotest</a>
	<span class="col-sm-9 px-sm-0 px-5 navbar-text text-right">Logged in as: {{ request.user }}</span>
	<a class="nav-item btn btn-outline-primary my-2 my-sm-0 px-5 px-sm-3" type="button" href="{% url 'logout' %}?next={% url 'login' %}">Log Out</a>
</nav>

<div class="container-fluid">
	<div class="row">
		<nav class="col-md-2 d-none d-md-block bg-light sidebar">
			<div class="sidebar-sticky">
				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
					<span>GENERAL</span>
				</h6>
				<ul class="nav flex-column">
					<li class="nav-item">
						{% url 'main' as url %}
						<a href="{{ url }}"
							{% if request.path == url %}
							class="nav-link active"
							{% elif request.path == '/' %}
							class="nav-link active"
							{% else %}
							class="nav-link"
							{% endif %}
						>Main</a>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link">Profile</a>
					</li>
					{% if request.user.is_admin == True %}
					<li class="nav-item">
						<a href="/admin" class="nav-link">Django Administration</a>
					</li>
					{% endif %}
				</ul>

				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
					<span>EXAMS</span>
				</h6>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link" href="#">
							Create new exam
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							All exams
						</a>
					</li>

				</ul>

				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
					<span>COURSES</span>
				</h6>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link" href="#">
							View/edit existing courses
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							Add a course
						</a>
					</li>
				</ul>


				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
					<span>OBJECTIVES</span>
				</h6>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link" href="#">
							View/edit existing objectives
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							Add an objective
						</a>
					</li>
				</ul>

				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
					<span>QUESTIONS</span>
				</h6>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link" href="#">
							View/edit existing questions
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							Add a question
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							Bulk question import tool
						</a>
					</li>
				</ul>

			</div>
		</nav>
	</div>
</div>